import {
  Activity,
  BookCheck,
  ClipboardList,
  Clock,
  Code2,
  Eye,
  FileSearch,
  Gauge,
  Globe,
  Heart,
  KeyRound,
  Landmark,
  LineChart,
  ListChecks,
  Lock,
  MessageCircle,
  Mic,
  PhoneCall,
  Plug,
  RefreshCw,
  Server,
  ShieldAlert,
  ShieldCheck,
  Stethoscope,
  TrendingUp,
  UserCheck,
  Users,
  Workflow,
} from 'lucide-react'

/** Maps the icon keys used in the translation files to lucide components. */
const ICONS = {
  activity: Activity,
  'book-check': BookCheck,
  'clipboard-list': ClipboardList,
  clock: Clock,
  code: Code2,
  eye: Eye,
  'file-search': FileSearch,
  gauge: Gauge,
  globe: Globe,
  heart: Heart,
  'key-round': KeyRound,
  landmark: Landmark,
  'line-chart': LineChart,
  'list-checks': ListChecks,
  lock: Lock,
  'message-circle': MessageCircle,
  mic: Mic,
  'phone-call': PhoneCall,
  plug: Plug,
  'refresh-cw': RefreshCw,
  server: Server,
  'shield-alert': ShieldAlert,
  'shield-check': ShieldCheck,
  stethoscope: Stethoscope,
  'trending-up': TrendingUp,
  'user-check': UserCheck,
  users: Users,
  workflow: Workflow,
}

export default function Icon({ name, ...props }) {
  const Cmp = ICONS[name] ?? Activity
  return <Cmp aria-hidden="true" {...props} />
}
